export const SET_USERS  = 'SET_USERS';
export const SET_USERS_IS_LOADING = 'SET_USERS_IS_LOADING';
export const RESET_USERS_IS_LOADING = 'RESET_USERS_IS_LOADING';
export const SET_USERS_ERROR = 'SET_USERS_ERROR';